apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "913791"

---
apiVersion: v1
kind: Secret
metadata:
  name: external-api-secrets
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: ""
  TWILIO_ACCOUNT_SID: ""
  TWILIO_AUTH_TOKEN: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "stockdb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD_FILE
              value: "/etc/secrets/POSTGRES_PASSWORD"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-secret-volume
          secret:
            secretName: postgres-secret

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: retainai
  ports:
    - name: backend
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: frontend
      protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30573

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retainai
  template:
    metadata:
      labels:
        app: retainai
    spec:
      containers:
        - name: retainai-container
          image: err0rz/retainx:latest
          ports:
            - containerPort: 8000
            - containerPort: 5173
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_NAME
              value: "stockdb"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-api-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: external-api-secrets
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-api-secrets
                  key: TWILIO_AUTH_TOKEN